# Generated by Django 3.0.4 on 2020-05-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='body',
            field=models.TextField(default='', max_length=4096),
            preserve_default=False,
        ),
    ]
