# Generated by Django 3.0.4 on 2020-05-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_comment_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='_comment_comments_+', to='films.Comment'),
        ),
    ]
