# Generated by Django 3.0.4 on 2020-05-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0006_auto_20200510_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='trailer_url',
            field=models.URLField(default='youtube.com', max_length=512),
            preserve_default=False,
        ),
    ]
